settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: git-hook
  path: ./cmd/server
  commands:
    install:
      status: true
      method: go build -o ../../debug
    run:
      status: true
      method: ./debug
  watcher:
    extensions:
    - go
    paths:
    - ../../
    ignored_paths:
    - .git
    - .realize
    - vendor